### ISSUE TITLE
Uncaught exception 'RuntimeException' with message 'Could not establish Memcached connection.'

### ISSUE THREAD

**Issue by rahul-rkt** [atyagi/elasticache-laravel#15]
I am getting this issue. We are running Laravel 4.2 and using your `"atyagi/elasticache-laravel": "~1.1"`.

I've tried setting the driver as memcached & elasticache, and I'm using the endpoints from Amazon.

`\nFatal error: Uncaught exception 'RuntimeException' with message 'Could not establish Memcached connection.' in /home/vagrant/musejam-app/vendor/atyagi/elasticache-laravel/src/Atyagi/Elasticache/ElasticacheConnector.php:32\nStack trace:\n#0 /home/vagrant/musejam-app/vendor/atyagi/elasticache-laravel/src/Atyagi/Elasticache/ElasticacheServiceProvider.php(22): Atyagi\\Elasticache\\ElasticacheConnector->connect()\n#1 /home/vagrant/musejam-app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(317): Atyagi\\Elasticache\\ElasticacheServiceProvider->register()\n#2 /home/vagrant/musejam-app/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(82): Illuminate\\Foundation\\Application->register()\n#3 /home/vagrant/musejam-app/vendor/laravel/framework/src/Illuminate/Foundation/start.php(195): Illuminate\\Foundation\\ProviderRepository->load()\n#4 /home/vagrant/musejam-app/bootstrap/start.php(62): include()\n#5 /home/vagrant/musejam-app/public/index.php(47): include()\n#6 {main}`

**Comment by rahul-rkt** [comment]
I tried to log `\Memcached::OPT_CLIENT_MODE` then I got this fatal -

`\nFatal error: Couldn't find constant Memcached::OPT_CLIENT_MODE in /home/vagrant/musejam-app/vendor/atyagi/elasticache-laravel/src/Atyagi/Elasticache/ElasticacheConnector.php on line 19`

**Comment by atyagi** [comment]
Did you install Memcached into the PHP runtime via a pecl install? Based on the second error it sounds like Memcached doesn't exist in the runtime.

**Comment by rahul-rkt** [comment]
I am using Laravel Homestead, and I can see Memcached running when I do `service memcached status`.

**Comment by atyagi** [comment]
Please read the first line in the `Setup` section - for PHP to communicate to memcached, you need to install the memcached driver for PHP. Here is the link - http://php.net/manual/en/book.memcached.php

**Comment by atyagi** [comment]
@rahul-rkt Are you still seeing this issue? If not, I'm going to close it.

**Comment by whobutsb** [comment]
I was getting this same exact error.  I believe you need to install the ElastiCache Client PHP Module, instead of using the normal php5-memcached module - http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Appendix.PHPAutoDiscoverySetup.html
