### ISSUE TITLE
Using Amazon ElastiCache Cluster Client

### ISSUE THREAD

**Issue by whobutsb** [atyagi/elasticache-laravel#16]
Hello!  I'm working on using the Elasticache in my application.  My question is do you need to use the Amazon ElastiCache Cluster Client PHP Module as described here - http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Appendix.PHPAutoDiscoverySetup.html in conjunction with your library.  Or can you just use the ElastiCache PHP Module and the normal Laravel memcached driver?  

Its all pretty confusing on how they have it setup.  I was under the assumption Elasticache was a drop in replacement for memcached. Thank you in advance for the clarification!

**Comment by atyagi** [comment]
With the library here, it's a drop in replacement. You don't need to use the auto discovery setup.

**Comment by whobutsb** [comment]
Ok thank you!  Have you had any experience using the ElastiCache Cluster Client?  I went the opposite, installed the Client module, and using the default memcached connector with laravel.

**Comment by atyagi** [comment]
Unfortunately no. Good luck!
