### ISSUE TITLE
Login redirected to login on setup Elasticache

### ISSUE THREAD

**Issue by NestorAcevedo** [atyagi/elasticache-laravel#18]
Hi, using this package and configuring Laravel 4.2 for using memcached as session driver results on a redirect to login.

I explain: on session.php I change the driver to memcached, and into memcached array I configure the host to elasticache endpoint. When I try to login with my username and password, in the laravel log I can see the app routes to the page configured, but what actually happens is the browser redirects again to login page.

Does I need to setup some additional to work with this package?

**Comment by atyagi** [comment]
Hmm, I'd need to see more info as to what's going on - can you look at the trace of requests going through your browser to see? 

The fact that the app is booting up is a good thing because it sounds like you're able to connect to the actual cache endpoint.

**Comment by NestorAcevedo** [comment]
Hi, I could check I get a double status 302 as shown in the image
![instantanea43](https://cloud.githubusercontent.com/assets/438372/20024589/8fca6654-a2b5-11e6-97e1-ebfa7a467a75.png)
the first one "verify" is made once the login is correct
the second one is the dashboard where I should to arrive but that's the problem. I am being redirected to the login page.

I think is more than a PHP bug or some related to elasticache config although the security group is open to world.

**Comment by atyagi** [comment]
Got it, so when you've hit the dashboard, it doesn't look like it registered the session upon login. Have you confirmed your login code actually creates the user's session?

**Comment by NestorAcevedo** [comment]
yes. if I enable cookie I can login and access to Dashboard. it happens in my local environment and also in server production.

**Comment by atyagi** [comment]
Ok. How are you setting up your credentials to connect to the elasticache endpoint?

**Comment by NestorAcevedo** [comment]
Yes, I did it at first time.

**Comment by atyagi** [comment]
What's your configuration on the main driver in the session.php file? That driver needs to be elasticache, not memcached.

**Comment by NestorAcevedo** [comment]
Did it with same results

**Comment by atyagi** [comment]
Does your server have access to the elasticache endpoint? You'll need to make sure the AWS security groups are set up correctly so that the application can hit elasticache.

**Comment by NestorAcevedo** [comment]
Yes, SG group is open to all as I mentioned. I can telnet from my EB server and I can write/read on elasticache: 
![imagen](https://cloud.githubusercontent.com/assets/438372/20678841/464d2f84-b566-11e6-867a-44a9c99f4fec.png)

**Comment by atyagi** [comment]
Unfortunately I'm out of typical issues that would pop up. I'd need a few more error logs from your webapp to determine what's actually going on. You can try adding a few echo statements on your server's php files to see what's going on.

**Comment by NestorAcevedo** [comment]
good, now the situation is a bit strange. I am currently seeing all stats into elasticache: connections, number of objects and so on and doing again a telnet I could check session vars and the redirect loop has disappeared for now O.o

I don't know how and why, but now looks it works as is expected:

> 
add laravel_session_713e9a374076045fcf18950a356243e353cd75ad 0 1480444994 197
a:3:{s:6:"_token";s:40:"TOKEN_HASH";s:9:"_sf2_meta";a:3:{s:1:"u";i:1480437794;s:1:"c";i:1480437794;s:1:"l";s:1:"0";}s:5:"flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}
 
I have laravel in debug mode and still I didn't have any error with this. I will leave opened it meanwhile.

Regards.

**Comment by NestorAcevedo** [comment]
Is strange, I have just launched a new EB environment with same source code and the problem appears again:

> internal_ip (my_ip) - - [29/Nov/2016:13:59:49 -0500] "POST /admin/verify HTTP/1.1" 302 4877 "http://new_url/admin/login" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
internal_ip (my_ip) - - [29/Nov/2016:13:59:49 -0500] "GET /admin/dashboard HTTP/1.1" 302 4864 "http://new_url/admin/login" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
internal_ip (my_ip) - - [29/Nov/2016:13:59:50 -0500] "GET /admin/login HTTP/1.1" 200 3580 "http://new_url/admin/login" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0)

And checking laravel.log or error_log doesn't show anything

**Comment by NestorAcevedo** [comment]
It's ok, I could see elasticache is not reached from anyother site except ec2 server pre-configured so I reconfigured it and now works.
