### ISSUE TITLE
Can't make it work in my Laravel app

### ISSUE THREAD

**Issue by kintso** [atyagi/elasticache-laravel#2]
Thanks for your code! I am trying to use it for an application deployed on Heroku.

I did follow the set up instructions you provided and have in my composer.json "atyagi/elasticache-laravel": "1.1._" and "ext-memcached": "_",

In the cache.php config file relative to my environment I did set the driver as elasticache and in the memcached array I have

```
            array(                    
                'host' => 'http://xxxx.yyyy.cache.amazonaws.com', 
                'port' => 11211, 
                'weight' => 100,)
```

Where host is the Configuration Endpoint provided in the Amazon Elasticache interface. However trying to test it with this code in a test route

```
        Cache::add('test', 'elasticache works', 60);
        $value = Cache::get('test', 'not working');
        return $value;
```

I always end up having 'not working'. 

Could you help me in understanding why I can't set it up properly? Or how can I investigate it further?

Many thanks

**Comment by atyagi** [comment]
Hey @kintso, awesome to hear! The code there looked good. Definitely worth open sourcing it and publishing out!

**Comment by kintso** [comment]
Thanks! I made it available on https://github.com/kintso/memcachedcloud-laravel. Let me know if you have trouble using it from there. It is my first public repo on Github
