### ISSUE TITLE
Laravel 5 problem - installable set of packages

### ISSUE THREAD

**Issue by jr2wolfgang** [atyagi/elasticache-laravel#3]
I ran composer update but I got errors like these:

 - Installation request for atyagi/elasticache-laravel dev-master -> satisfiable by atyagi/elasticache-laravel[dev-master].
    - laravel/framework 5.0.x-dev requires league/flysystem ~1.0 -> satisfiable by league/flysystem[1.0.x-dev].
    - Can only install one of: league/flysystem[1.0.x-dev, 0.6.x-dev].
    - Installation request for league/flysystem == 0.6.9999999.9999999-dev -> satisfiable by league/flysystem[0.6.x-dev].

and there's long list. I suspect that the main issue was because I have laravel 5 installed and that this plugin is not ready yet for L5?

any ideas?

**Comment by atyagi** [comment]
Hey @jr2wolfgang , 

I currently have a branch for Laravel 5 - " feature-laravel5" that you can use for your project.

Your composer.json would look like this: 

```
require: {
    ...
    "atyagi/elasticache-laravel": "dev-feature-laravel5"
}
```

Note that while Laravel 5 is in alpha, I can't guarantee that this package will work with Laravel 5 as version 5 is changing all the time. 

Best of luck!

**Comment by jr2wolfgang** [comment]
Wow, that was fast.. I thought it will took me days for your response. My only question right now is:
where can I put my configuration to connect to Elasticache? is it on the app/session.php as well?

**Comment by atyagi** [comment]
The connection configuration sits within app/cache.php using the memcached key. Take a look at the Laravel Cache Memcached configuration to see how the specific keys work.

**Comment by jr2wolfgang** [comment]
It worked! I'll do some couple of things just to check if everything seems to work smoothly

**Comment by jr2wolfgang** [comment]
Everything worked for me now.. Thanks for your great plugin..

**Comment by atyagi** [comment]
@jr2wolfgang Glad to hear! Thank you!
