### ISSUE TITLE
Settings page?

### ISSUE THREAD

**Issue by jr2wolfgang** [atyagi/elasticache-laravel#4]
This plugin is having some issue because there's no settings page.
Can you post here or in your README file an example on how to at least connect to Elasticache using your plugin?

**Comment by atyagi** [comment]
Hi @jr2wolfgang ,

I'm a little unsure of what you mean by a settings page. The configuration to connect to Elasticache clusters uses the 'memcached' key in the cache.php configuration file as part of the framework. 

If you look at https://github.com/laravel/laravel/blob/master/app/config/cache.php#L70 you can see how to configure your nodes to be used by the plugin. 

Let me know if you have any more questions.

**Comment by atyagi** [comment]
@jr2wolfgang Since I haven't heard from you in a bit I'm going to close this issue. Hopefully you were able to connect. Feel free to let me know if you're still having trouble.

**Comment by jr2wolfgang** [comment]
sorry for the late response but yeah, I was able to connect using the
elasticache for L5.

**Comment by atyagi** [comment]
Great to hear!
