### ISSUE TITLE
Driver [elasticache] not supported.

### ISSUE THREAD

**Issue by boadude** [atyagi/elasticache-laravel#6]
In the app/session.php i put:

<code>
'driver' => 'elasticache',
</code>

And say that, what is wrong?

**Comment by atyagi** [comment]
Can you provide a little more information? Did you add the service provider to your providers array in config/app.php?

**Comment by boadude** [comment]
Yes... first run the <code>composer update</code> then add the provide

<code>
'providers' => array(
                ...
		'Atyagi\Elasticache\ElasticacheServiceProvider',
                ...
	),
</code>

and my <code>composer.json</code> is:

<code>
...
"require": {
		...
		"atyagi/elasticache-laravel": "~1.1",
               ...
	},
</code>

**Comment by boadude** [comment]
Is for Laravel 4...

**Comment by boadude** [comment]
What about this message when install the extension

<code>
atyagi/elasticache-laravel suggests installing ext-memcached (Leverage the Memca
ched extension for Elasticache connections.)
</code>

**Comment by atyagi** [comment]
That's probably it - you need to install Memcached for the plugin to register. See this line - https://github.com/atyagi/elasticache-laravel/blob/1.1.8/src/Atyagi/Elasticache/ElasticacheServiceProvider.php#L24

The history behind that sits in #5 - you can look there for more reasoning as to why I went with this route after discussion.

Installation instructions for memcached are found here - http://php.net/manual/en/book.memcached.php

**Comment by boadude** [comment]
Ok, install the php_memcached.dll extension on my php ext and restart... nothing happent... same error

**Comment by boadude** [comment]
The route of the error is in:

<code>laravel\framework\src\Illuminate\Support\Manager.php:91</code>
with the message:
<code>throw new \InvalidArgumentException("Driver [$driver] not supported.");</code>

**Comment by boadude** [comment]
Ok, i am back :P

So i install php5-memcached and now i got this error:

<code>Class session does not exist</code>

In this line:

<code>
$this->app->make('session')->extend('elasticache', function () use ($memcached) {
                return new ElasticacheSessionHandler($memcached, $this->app);
            });
</code>

**Comment by boadude** [comment]
Now i am running in Ubuntu 14.04

**Comment by boadude** [comment]
Now: if i comment the this line on the providers

<code>
/*
            $this->app->make('session')->extend('elasticache', function () use ($memcached) {
                return new ElasticacheSessionHandler($memcached, $this->app);
            });
            */
</code>

Works!... very strange

**Comment by atyagi** [comment]
Interesting - I'm not sure why `$this->app->make('session')` would be trying to create a 'session' class as it should be trying to resolve the SessionManager from the IoC container. 

Can you check to make sure the Session Manager is inside of the IoC container before it hits the ElasticacheServiceProvider?

**Comment by boadude** [comment]
Ok, that work!... my mistake was i put

<code>
Atyagi\Elasticache\ElasticacheServiceProvider
</code>

before:

<code>
Illuminate\Session\SessionServiceProvider
</code>

**Comment by boadude** [comment]
I wanna add something... for use this pluggin i must install "php5-memcached" but i my app now work very slow...

**Comment by atyagi** [comment]
Perfect, glad to hear!

With your app responding slowly, it depends on multiple factors. Where is your app actually hosted? 

If you're using Elasticache locally, there's a chance that it may be slow since you're making an external network call.

**Comment by boadude** [comment]
My app is hosted in the same Region and AZ that my ElastiCache node... i think is the library php5-memcached because if i dont used ... the app work fast...

but the strange here is i just configure the session
<code>'driver' => 'elasticache'</code>
even if i dont used the app is slow... for anything i do...

and the other thing is that my filter CSRF dont work... dont know why...

**Comment by boadude** [comment]
I cant understand why is sow slow natigate in my app when i install the php5-memcached

**Comment by boadude** [comment]
Ok... i figured now... the problem what the url endpoint of the elasticache... now the page work fast... but one problem left... <b>CSRF Token Missmatch</b>

**Comment by boadude** [comment]
Ok, found it, the problem is not about the library:

'domain' => 'IP'

I must define the IP or de URL of the app.
