### ISSUE TITLE
Configuration Endpoint (Memcached)

### ISSUE THREAD

**Issue by eselopio** [atyagi/elasticache-laravel#8]
When i configure the memcached.php i must put the <b>End Point of the Node</b>. Is there a way to select the <b>Configuration Endpoint (Memcached)</b> to the ElastiCache manage various nodes?

<code>
'memcached' => array(
		array('host' => 'XXX.0001.sae1.cache.amazonaws.com', 
			  'port' => 11211, 
			  'weight' => 300),

	),
</code>

**Comment by atyagi** [comment]
I believe this is due to the fact that AWS provides a specific memcached client install - see [here](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Appendix.PHPAutoDiscoverySetup.html)

**Comment by boadude** [comment]
I will install and install the client to see if works!

**Comment by atyagi** [comment]
Any updates @boadude or @eselopio ?

**Comment by boadude** [comment]
Nothing yet. Still using one node so it's not necesary use the End point yet.

**Comment by atyagi** [comment]
I see. If it's ok with you, I'd like to close this issue then until there's something more to report.

**Comment by boadude** [comment]
Sure, no problem!
